### ISSUE TITLE
Visual Studio plugin does not launch Visual Studio Insiders 

### ISSUE THREAD

**Issue by squidds** [Odotocodot/VisualStudio4Flow#6]
I have MS Visual Studio Insiders installed, not the stable version. Version I have is installed through Choco package manager. I am not sure if this plugin can be adjusted to secondarily look for the Insiders (or any one of the other forks or versions) but her is what I am seeing:

[2024-03-26.txt](https://github.com/Odotocodot/VisualStudio4Flow/files/14763864/2024-03-26.txt)

```
Flow Launcher version: 1.17.2
OS Version: 22621.3296
IntPtr Length: 8
x64: True

Python Path: C:\Users\Administrator\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 03/26/2024 15:37:48
Exception:
Visual Studio Launcher Exception: 
Websites: https://github.com/Odotocodot/VisualStudio4Flow
Author: Odotocodot
Version: 1.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.VisualStudio.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Odotocodot** [comment]
The plugin finds installations using vswhere.exe, so the issue could be due to vswhere not being installed with VS insiders or from Chocolatey. I have already enabled it to find prerelease versions of VS if that helps at all!

**Comment by squidds** [comment]
> The plugin finds installations using vswhere.exe, so the issue could be due to vswhere not being installed with VS insiders or from Chocolatey. I have already enabled it to find prerelease versions of VS if that helps at all!

Issue seems to be resolved: 
![raw](https://github.com/Odotocodot/VisualStudio4Flow/assets/64927214/f586d709-96a3-4f74-9393-72a43902c500)

Thank you.
