### ISSUE TITLE
Visual Studio 22

### ISSUE THREAD

**Issue by KuyomieKurama** [Odotocodot/VisualStudio4Flow#8]
Hello Odotocodot,

I am a developer using Visual Studio 2022. I found your plugin very interesting but somehow it does not work with VS 2022. Could you make the plugin work with it?

I'll also post my log here in case this helps you.
[2024-09-06.txt](https://github.com/user-attachments/files/16905505/2024-09-06.txt)

**Comment by Odotocodot** [comment]
Hey, 
Hmm I'm using Visual Studio 2022, my version is 17.9.6 and _it works fine on my machine_
What version of Visual Studio 2022 are you using?
Does it crash when you search with the keyword or does it never load in Flow Launcher?

**Comment by KuyomieKurama** [comment]
Hey, 
i am using VS Professional 17.11.2. It does never Load. The extension crashes cause a Null Reference error :/

**Comment by Odotocodot** [comment]
Hmm, i'm using the community version, could you test it with that? As ive updated mine to 17.11.2 and it still works. 

The log indicates that it loads but when you try and use the plugin i.e. use the action keyword "[" it then crashes.

Does the failed to Init plugins notification pop up for it at all?

Also is it visible in the Flow Launcher Plugins tab like below?

![Screenshot 2024-09-10 004351](https://github.com/user-attachments/assets/303bcc5c-d7fc-4a2e-9c7e-16760ab8246d)
If its visible:
- Can you check the default open with dropdown and see if your VS instance is shown.
- Force a backup of recent items

Lastly can you see if you have a settings file for the plugin, its typically located at:
`C:\Users\<USERNAME>\AppData\Roaming\FlowLauncher\Settings\Plugins\Flow.Launcher.Plugin.VisualStudio`
and view the entries in the settings file checking the `FullPath` property look like, cause the null reference is coming from an invalid path to an project it seems.

**Comment by MelodyDuplaix** [comment]
Hello,
It seems that I have the same error.

My log file:  [2024-10-13.txt](https://github.com/user-attachments/files/17357138/2024-10-13.txt)
And the log message:
```
Flow Launcher version: 1.19.2
OS Version: 22631.4317
IntPtr Length: 8
x64: True

Python Path: C:\Users\melos\AppData\Local\Programs\Python\Python311\pythonw.exe
Node Path: C:\Users\melos\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 10/13/2024 23:34:55
Exception:
Visual Studio Launcher Exception: 
Websites: https://github.com/Odotocodot/VisualStudio4Flow
Author: Odotocodot
Version: 1.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.VisualStudio.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

For me, when FlowLauncher start, The failed to Init plugins notification pop up appear. Then, when I try to load manually the plugin, it doesn't.

The settings for the plugins are also not complete:

![image](https://github.com/user-attachments/assets/45faef63-6ef9-4cb2-9ccd-7a688b8cefa7)

Finally, the setting file of the plugin is also weird: 
```
{
  "DefaultVSId": null,
  "AutoUpdateBackup": true,
  "LastBackup": "0001-01-01T00:00:00",
  "EntriesBackup": null
}
```

**Comment by Odotocodot** [comment]
Hello, thanks for the message.
Been working on this, the null reference exception is due to the plugin failing to init.
And it seems to be failing because it cannot find `vswhere.exe`.

Heres a preview of the new version:
[Visual Studio Launcher-1.0.3.zip](https://github.com/user-attachments/files/17368580/Visual.Studio.Launcher-1.0.3.zip)
I believe you will have find where `vswhere.exe` is installed on your system and change the new plugin setting to match it.

**Comment by MelodyDuplaix** [comment]
Oh, I have found the problem, It's a bit… awkward. I had forgotten the existence of Visual Studio in place of Visual Studio Code, and so since it's often abbreviated, I concluded that this plugin was for Visual Studio Code. Obviously, Visual Studio is not installed on my computer, so it couldn't work.
Thanks anyway for the help.

**Comment by Odotocodot** [comment]
Haha no worries, glad the problem has been solved!

**Comment by KuyomieKurama** [comment]
with the new version you provided, that works for me thanks

**Comment by Odotocodot** [comment]
@KuyomieKurama good to know. Did you have to change the vswhere.exe path then?

**Comment by KuyomieKurama** [comment]
@Odotocodot no, i didn't change the path.

**Comment by Odotocodot** [comment]
Wait really? Thats strange because nothing else was changed functionality wise other than making the vswhere.exe path mutable!
